---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/hermesgarcia/public_html/projects/vanillajs/
    - export DEPLOYPATH1=/home3/hermesgarcia/public_html/projects/vanillajs/accordion
    - export DEPLOYPATH2=/home3/hermesgarcia/public_html/projects/vanillajs/petfinder
    - export DEPLOYPATH3=/home3/hermesgarcia/public_html/projects/vanillajs/countdown
    - export DEPLOYPATH4=/home3/hermesgarcia/public_html/projects/vanillajs/monsters
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp accordion/index.html $DEPLOYPATH1
    - /bin/cp petfinder/index.html $DEPLOYPATH2
    - /bin/cp countdown/index.html $DEPLOYPATH3
    - /bin/cp monsters/index.html $DEPLOYPATH4
    - /bin/cp -R /home3/hermesgarcia/repositories/vanillaJS/accordion/assets $DEPLOYPATH1
    - /bin/cp -R /home3/hermesgarcia/repositories/vanillaJS/petfinder/assets $DEPLOYPATH2
    - /bin/cp -R /home3/hermesgarcia/repositories/vanillaJS/countdown/assets $DEPLOYPATH3
    - /bin/cp -R /home3/hermesgarcia/repositories/vanillaJS/monsters/assets $DEPLOYPATH4
